#!/usr/bin/env bash
# Configure the Authelia file backend headlessly (F7-B).
#
#   1. verify the declared admin can pass first factor
#   2. otherwise regenerate the argon2id hash of AUTHELIA_ADMIN_PASSWORD and
#      write users_database.yml (repo copy and the copy the container mounts)
#
# Only the hash is ever written; the plaintext never leaves the secret cache.
# The jwt/session/storage secrets are injected as env vars by compose, not here.
#
# Usage:
#   ./utils/bootstrap/authelia.sh --env dev [--host 127.0.0.1]
#
# Exit: 0 configured, 2 container absent, 1 failed.

HL_APP=authelia
HL_USAGE_LINES='2,15'
# shellcheck source=lib.sh
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"
hl_parse_args "$@"

CONTAINER="$(hl_service authelia container)"
PORT="$(hl_service authelia port)"
BASE="https://${HOMELAB_HOST}:${PORT}"
USERNAME="$(hl_account authelia username)"
EMAIL="$(hl_account authelia email)"
PASSWORD="$(hl_secret "$(hl_account authelia secret)")"
USERS_FILE="$(hl_compose_dir)/core/authelia/users_database.yml"
REPO_USERS_FILE="${HL_REPO_ROOT}/compose/core/authelia/users_database.yml"

hl_require_container "$CONTAINER"

first_factor_ok() {
  local body response
  # Cookie domain is homelab.local — posting to a raw IP fails with
  # "no configured session cookie domain matches the url".
  body="{\"username\":$(hl_json_escape "$USERNAME"),\"password\":$(hl_json_escape "$PASSWORD"),\"keepMeLoggedIn\":false}"
  response="$(printf '%s' "$body" |
    curl -sS -k --max-time 20 --resolve "authelia.homelab.local:${PORT}:127.0.0.1" \
      -X POST "https://authelia.homelab.local:${PORT}/api/firstfactor" \
      -H 'Content-Type: application/json' --data @- 2>/dev/null || true)"
  [[ "$response" == *'"status":"OK"'* ]]
}

render_users_file() {
  local hash="$1" target="$2"
  HL_HASH="$hash" HL_USER="$USERNAME" HL_EMAIL="$EMAIL" python3 - "$target" <<'PY'
import os, sys

sys.stdout = open(sys.argv[1], "w")
print("""---
# Authelia file backend — generated by utils/bootstrap/authelia.sh.
# The argon2id hash of AUTHELIA_ADMIN_PASSWORD is safe to commit; the plaintext is not.
# Regenerate after a rotation:
#   ./utils/bootstrap/authelia.sh --env dev
users:
  {user}:
    disabled: false
    displayname: Homelab Admin
    password: '{hash}'
    email: {email}
    groups:
      - admins""".format(
    user=os.environ["HL_USER"],
    hash=os.environ["HL_HASH"],
    email=os.environ["HL_EMAIL"],
))
PY
}

if [[ -z "${AUTHELIA_FORCE_REHASH:-}" ]] && first_factor_ok; then
  hl_log "admin ${USERNAME} already passes first factor"
  hl_log "OK"
  exit 0
fi

hl_log "regenerating the argon2id hash for ${USERNAME}"
# `authelia crypto hash` only takes --password and refuses a non-interactive
# prompt, so the value is handed to the container through the environment and
# expanded inside it — it never reaches this host's command line.
HASH="$(docker exec -e HL_PW="$PASSWORD" "$CONTAINER" \
  sh -c 'authelia crypto hash generate argon2 --no-confirm --password "$HL_PW"' 2>/dev/null || true)"
HASH="$(printf '%s' "$HASH" | sed -n 's/^Digest: //p')"
[[ "$HASH" == \$argon2id\$* ]] || hl_die "authelia crypto hash generate did not return a digest"

render_users_file "$HASH" "$USERS_FILE"
hl_log "wrote ${USERS_FILE}"
if [[ -f "$REPO_USERS_FILE" && "$REPO_USERS_FILE" != "$USERS_FILE" ]]; then
  render_users_file "$HASH" "$REPO_USERS_FILE"
  hl_log "wrote ${REPO_USERS_FILE} (commit it — the hash is not a secret)"
fi

# `watch: true` reloads the file, but a restart is the reliable path after a
# permission or mount change.
sleep 3
if ! first_factor_ok; then
  hl_log "reloading Authelia"
  docker restart "$CONTAINER" >/dev/null
  hl_wait_http "${BASE}/api/health" "200" 90 || true
  sleep 3
fi
first_factor_ok || hl_die "first factor still fails for ${USERNAME}"
hl_log "admin ${USERNAME} converged"
hl_log "OK"
