# Prod — ubuntu-apps on APP VLAN (F3); ubuntu-nas on IOT (F5)
[ubuntu_docker]
ubuntu-apps ansible_host=192.168.50.30 ansible_user=ubuntu

[ubuntu_nas]
ubuntu-nas ansible_host=192.168.20.12 ansible_user=ubuntu

[all:children]
ubuntu_docker
ubuntu_nas
