---
- name: Wait till machine is online to estabilish SSH connection
  hosts: ubuntu-docker
  become: false
  tasks:
    - name: Waiting for SSH port to be available when Terraform triggers restart
      ansible.builtin.wait_for_connection:
        timeout: 180
        delay: 5
