---
- hosts: ubuntu-docker
  become: true
  vars:
    postgres_password: "{{ lookup('env', 'POSTGRES_PASSWORD') }}"
    ubuntu_docker_password: "{{ lookup('env', 'UBUNTU_DOCKER_PASSWORD') }}"
    deploy_env: "{{ lookup('env', 'DEPLOY_ENV') }}"
    containers:
      - name: postgres
        image: postgres:17
        ports:
          - "5432:5432"
        env:
          POSTGRES_PASSWORD: "{{ postgres_password }}"
        volumes:
          - /opt/postgres:/var/lib/postgresql/data
      - name: pgadmin
        image: dpage/pgadmin4:latest
        ports:
          - "5050:80"
        env:
          PGADMIN_DEFAULT_EMAIL: admin@local.com
          PGADMIN_DEFAULT_PASSWORD: admin
          PGADMIN_CONFIG_SERVER_MODE: "False"
        volumes:
          - /opt/pgadmin:/var/lib/pgadmin
          - /opt/pgadmin/servers.json:/var/lib/pgadmin/servers.json

  tasks:
    - name: Install Python dependencies
      apt:
        name: python3-psycopg2
        state: present
      become: true

    - name: Ensure pgAdmin sessions directory exists with correct permissions
      file:
        path: /opt/pgadmin/sessions
        state: directory
        owner: 5050
        group: 5050
        mode: "0700"

    - name: Set permissions recursively for /opt/pgadmin directory
      file:
        path: /opt/pgadmin
        recurse: yes
        owner: 5050
        group: 5050
        mode: "0700"

    - name: Deploy pgAdmin servers.json config
      template:
        src: environments/{{ deploy_env }}/pdAdminServers.json.j2
        dest: /opt/pgadmin/servers.json
        owner: 5050
        group: 5050
        mode: "0600"

    - name: Pull and run all defined DB containers
      community.docker.docker_container:
        name: "{{ item.name }}"
        image: "{{ item.image | default(omit) }}"
        build: "{{ item.build | default(omit) }}"
        ports: "{{ item.ports | default(omit) }}"
        volumes: "{{ item.volumes | default(omit) }}"
        env: "{{ item.env | default(omit) }}"
        restart_policy: always
        state: started
      loop: "{{ containers }}"

    - name: Create application databases
      community.postgresql.postgresql_db:
        name: "{{ item }}"
        login_user: postgres
        login_password: "{{ postgres_password }}"
        login_host: 192.168.122.221
        login_port: 5432
      loop:
        - linkwarden
        - firefly3
        - easytodo
        - authelia
        - nginx

    - name: Create PostgreSQL users for each database
      community.postgresql.postgresql_user:
        name: "{{ item }}"
        password: "{{ postgres_password }}"
        login_db: "{{ item }}"
        login_user: postgres
        login_password: "{{ postgres_password }}"
        login_host: 192.168.122.221
        login_port: 5432
      loop:
        - linkwarden
        - firefly3
        - easytodo
        - authelia
        - nginx

    - name: Grant privileges for PostgreSQL users
      community.postgresql.postgresql_query:
        login_user: postgres
        login_password: "{{ postgres_password }}"
        login_host: 192.168.122.221
        login_port: 5432
        login_db: "{{ item }}"
        query:
          - "GRANT ALL PRIVILEGES ON DATABASE {{ item }} TO {{ item }};"
          - "GRANT ALL PRIVILEGES ON SCHEMA public TO {{ item }};"
          - "ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO {{ item }};"
      loop:
        - linkwarden
        - firefly3
        - easytodo
        - authelia
        - nginx
