- hosts: ubuntu-docker
  become: true
  vars:
    postgres_password: "{{ lookup('env', 'POSTGRES_PASSWORD') }}"
    ubuntu_docker_password: "{{ lookup('env', 'UBUNTU_DOCKER_PASSWORD') }}"
  tasks:
    - name: Create ubuntu user with password
      user:
        name: ubuntu
        password: "{{ ubuntu_docker_password | password_hash('sha512') }}"
        shell: /bin/bash
        groups: sudo,docker
        append: yes
        state: present
        create_home: yes
