name: Manuallly Triggered Workflow

on:
  workflow_dispatch:
    inputs:
      value1:
        description: "Value 1"
        required: true
        default: "Value 1"
      value2:
        description: "Value 2"
        required: false
        default: "Value 2"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Echo parameters
        run: |
          echo "Value 1: ${{ github.event.inputs.value1 }}"
          echo "Value 2: ${{ github.event.inputs.value2 }}"
