name: Setup Proxmox VMs

on:
  push:
    branches: ["dev", "main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  Setup_Proxmox_VMs:
    runs-on: self-hosted
    environment: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}
    env:
      TF_VAR_environment: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.0

      - name: Prepare Terraform environment directory
        run: |
          mkdir -p $HOME/HomeLab/git/actions-runner/terraform/states/$TF_VAR_environment
          chmod -R 700 $HOME/HomeLab/git/actions-runner/terraform/states/$TF_VAR_environment

      - name: Terraform Init & Apply
        env:
          TF_VAR_proxmox_api_url: ${{ vars.PROXMOX_API_URL }}
          TF_VAR_proxmox_api_token_id: ${{ vars.PROXMOX_API_TOKEN_ID }}
          TF_VAR_proxmox_api_token_secret: ${{ secrets.PROXMOX_API_TOKEN_SECRET }}
          TF_VAR_proxmox_ssh_username: ${{ vars.PROXMOX_SSH_USERNAME }}
          TF_VAR_proxmox_ssh_password: ${{ secrets.PROXMOX_SSH_PASSWORD }}
          TF_VAR_ubuntu_password: ${{ secrets.UBUNTU_PASSWORD }}
        run: |
          mkdir -p $(pwd)/terraform/terraform.tfstate.d/$TF_VAR_environment

          if [ -f "$HOME/HomeLab/git/actions-runner/terraform/states/$TF_VAR_environment/terraform.tfstate" ]; then
            echo "terraform.tfstate exists. Last state will be used for provisioning."
            cp $HOME/HomeLab/git/actions-runner/terraform/states/$TF_VAR_environment/terraform.tfstate $(pwd)/terraform/terraform.tfstate.d/$TF_VAR_environment/terraform.tfstate
          else
            echo "terraform.tfstate doesn't exist. Initial provisioning will be performed."
          fi

          cd terraform
          terraform workspace select -or-create $TF_VAR_environment
          terraform init 
          terraform plan -var-file=environments/$TF_VAR_environment/terraform.tfvars
          terraform apply -auto-approve -var-file=environments/$TF_VAR_environment/terraform.tfvars

      - name: Copy Terraform tfstate
        run: |
          cp terraform/terraform.tfstate.d/$TF_VAR_environment/terraform.tfstate $HOME/HomeLab/git/actions-runner/terraform/states/$TF_VAR_environment/terraform.tfstate
