name: Setup Infrastructure

on:
  push:
    branches: ["dev", "main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  development:
    if: github.ref == 'refs/heads/dev'
    name: Development Environment Setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Secrets from Bitwarden
        uses: bitwarden/sm-action@v2
        with:
          access_token: ${{ secrets.BW_ACCESS_TOKEN }}
          secrets: |
            <SECRET_ID_DEVELOPMENT> > BW_TEST

      - name: Use Retrieved Secret
        run: |
          echo "Development Secret Value: $BW_TEST"

  production:
    if: github.ref == 'refs/heads/main'
    name: Production Environment Setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Secrets from Bitwarden
        uses: bitwarden/sm-action@v2
        with:
          access_token: ${{ secrets.BW_ACCESS_TOKEN }}
          secrets: |
            <SECRET_ID_PRODUCTION> > BW_TEST

      - name: Use Retrieved Secret
        run: |
          echo "Production Secret Value: $BW_TEST"
