name: Setup infrastructure

on:
  push:
    branches: ["dev", "main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  dev:
    if: github.ref == 'refs/heads/dev'
    name: Development Environment Setup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Bitwarden CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl
          curl -Lso bw.zip https://vault.bitwarden.com/download/?app=cli&platform=linux
          unzip bw.zip -d bw-cli
          sudo mv bw-cli/bw /usr/local/bin
          bw --version

      - name: Login to Bitwarden
        run: |
          export BW_SESSION=$(bw login --apikey --clientid "${{ secrets.BW_CLIENTID }}" --clientsecret "${{ secrets.BW_CLIENTSECRET }}" --raw)
          echo "BW_SESSION=$BW_SESSION" >> $GITHUB_ENV

      - name: Get BW_TEST secret from development
        run: |
          VALUE=$(bw get item BW_TEST --session "$BW_SESSION" | jq -r '.fields[] | select(.name=="development") | .value')
          echo "Secret Value: $VALUE"

  prod:
    if: github.ref == 'refs/heads/main'
    name: Production Environment Setup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Bitwarden CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl
          curl -Lso bw.zip https://vault.bitwarden.com/download/?app=cli&platform=linux
          unzip bw.zip -d bw-cli
          sudo mv bw-cli/bw /usr/local/bin
          bw --version

      - name: Login to Bitwarden
        run: |
          export BW_SESSION=$(bw login --apikey --clientid "${{ secrets.BW_CLIENTID }}" --clientsecret "${{ secrets.BW_CLIENTSECRET }}" --raw)
          echo "BW_SESSION=$BW_SESSION" >> $GITHUB_ENV

      - name: Get BW_TEST secret from production
        run: |
          VALUE=$(bw get item BW_TEST --session "$BW_SESSION" | jq -r '.fields[] | select(.name=="production") | .value')
          echo "Secret Value: $VALUE"
