name: Setup Homelab

on:
  push:
    branches: ["dev", "main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    environment: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Secrets
        uses: bitwarden/sm-action@v2
        with:
          access_token: ${{ secrets.BW_ACCESS_TOKEN }}
          secrets: |
            ${{ github.ref == 'refs/heads/main' && 'PROD_PROXMOX_API_TOKEN_SECRET' || '3d2f4daa-2567-4496-8b56-b2da00e9c9a7' }} > PROXMOX_API_TOKEN_SECRET

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.0

      - name: Terraform Init & Apply
        env:
          proxmox_api_url: ${{ vars.PROXMOX_API_URL }}
          proxmox_api_token_id: ${{ vars.PROXMOX_API_TOKEN_ID }}
          proxmox_api_token_secret: ${{ env.PROXMOX_API_TOKEN_SECRET }}
          environment: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}
        run: |
          cd ../../terraform
          terraform workspace select ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }} || terraform workspace new ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}
          terraform init
          terraform apply -auto-approve
